squash! LiteX: driver for MMCM
drivers/clk/clk-litex.c:1780:19: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
 1780 |         .remove = litex_clk_remove,
      |                   ^~~~~~~~~~~~~~~~

The error only shows up if your tree has commit 0edb555a65d1ef04
("platform: Make platform_driver::remove() return void", in
next-20240611 and later), but it is safe to apply this change before.

Once your tree has that commit, the hunk that does s/remove/remove_new/
can be dropped.